API_ID_KEY= "API_ID"
API_HASH_KEY = "API_HASH"  
STRING_SESSION = "AQAQwVcYjXn3XhZhpdJoO29q5sDCmCa1karny7uzgja_Fxkt6rcxz_fq049s3BWCb0q72F2vADGLPO-fQlcCwJHOoFiRxOtPCtfvJuad5Fa5Z8FYr19MFqGcnwTmOXvyd6l997NqlZJ-xnc5merNvda8xqNcSX0WQk3oO0VXnZ0mqIVOJ2b05ciLlkcIgwqy-b7U3vrRJX7S8Ss1guqbp7-NTLpygAxGJw9VKNNA3cSGreGQFL3nYHJD7-145LOxHOZgGpnYYzfGgWIN5KdMdHH43Bup7lXI4gVlUP8lB5xBUgK5IVrNj6mxd6zT4kw2Mf0VtXaOrtpgyozQ-DgKg6BAeNPgYAA"
MONGO_DB_URL = "MONGO_DB_URL"
Skynet = "Skynet"
ENFORCERS = "ENFORCERS"
INSPECTORS = "INSPECTORS"
Skynet_logs = "Skynet_logs"
Skynet_approved_logs = "Skynet_approved_logs"
GBAN_MSG_LOGS = "GBAN_MSG_LOGS"
BOT_TOKEN = "BOT_TOKEN"

    
    
    
    
